name: diffbind3
owner: inkuzmin
description: Diffbind provides functions for  processing  ChIP-Seq  data.
homepage_url: http://bioconductor.org/packages/release/bioc/html/DiffBind.html
long_description: Diffbind provides functions for  processing  ChIP-Seq  data  enriched  for  genomic  loci  where  specific  protein/DNA  binding  occurs,  including  peak sets  identified  by  ChIP-Seq  peak  callers  and  aligned  sequence  read  datasets. http://bioconductor.org/packages/release/bioc/html/DiffBind.html
type: unrestricted
categories:
- ChIP-seq
